name: Downstream CI
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  trigger-dbt-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dbt Cloud Downstream CI Action
      uses: dpguthrie/dbt-cloud-downstream-ci-action@0.4.0
      with:
        dbt_cloud_account_id: 43786
        dbt_cloud_job_id: 106109
        dbt_cloud_service_token: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
        dbt_cloud_host: 'cloud.getdbt.com'  # Optional
        pull_request_id: ${{ github.event.number }}
        git_sha: ${{ github.event.pull_request.head.sha }}
        github_token: ${{ secrets.GITHUB_TOKEN }}