name: Downstream CI
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  trigger-dbt-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dbt Cloud Downstream CI Action
      uses: dpguthrie/dbt-cloud-downstream-ci-action@v0.1.0
      with:
        dbt_cloud_account_id: ${{ secrets.ACCOUNT_ID }}
        dbt_cloud_job_id: ${{ secrets.JOB_ID }}
        dbt_cloud_service_token: ${{ secrets.SERVICE_TOKEN }}
